name: Zerodha News Analyzer

on:
  schedule:
    # Run at 9 AM and 10 PM IST (3:30 AM and 4:30 PM UTC)
    - cron: '30 3 * * *'  # 9 AM IST
    - cron: '30 16 * * *' # 10 PM IST
  workflow_dispatch:  # Allow manual trigger

jobs:
  analyze-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create data directory
        run: mkdir -p data

      - name: Run news analyzer
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python zerodha_news_analyzer.py

      - name: Create GitHub Release if it's 10 PM run
        if: github.event.schedule == '30 16 * * *'
        uses: softprops/action-gh-release@v1
        with:
          files: data/*.txt
          tag_name: news-analysis-${{ github.event.schedule == '30 16 * * *' && 'night' || 'morning' }}-${{ github.run_number }}
          name: News Analysis Report - ${{ github.event.schedule == '30 16 * * *' && 'Night' || 'Morning' }} Run
          body: |
            Automated news analysis report generated at ${{ github.event.schedule == '30 16 * * *' && '10 PM' || '9 AM' }} IST.
            
            This report contains:
            - Market news analysis
            - Sector-wise trends
            - Buy/Sell opportunities
            - Macro implications
            - Corporate actions
            
            Generated on: ${{ github.event.schedule == '30 16 * * *' && 'Night' || 'Morning' }} run
            Run number: ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 